handled 'writebbox' parameters for features and featurecollections
NetTopologySuite/NetTopologySuite.IO.GeoJSON pull request #101
Opened 2022-03-10 09:25 UTC by DGuidi

to fix #100

2022-03-10 15:05 UTC, LarryZhou commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjFeatureConverter.cs
> +            if (_writeBBox)
Great

2022-03-10 15:09 UTC, LarryZhou commented on test/NetTopologySuite.IO.GeoJSON4STJ.Test/Issues/Issue100.cs
> +                IgnoreNullValues = false,
This is deprecated, should use:

`DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,`

2022-03-10 15:09 UTC, LarryZhou commented on test/NetTopologySuite.IO.GeoJSON4STJ.Test/Issues/Issue100.cs
> +                IgnoreNullValues = false,
This is deprecated, should use:

`DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,`

2022-03-10 15:18 UTC, LarryZhou reviewed
Thanks you getting to this so quickly.  I left a question on the unut testing.

Also, how soon usually does it take for a fix like this get into a released package?

Larry

2022-03-10 15:58 UTC, DGuidi commented on test/NetTopologySuite.IO.GeoJSON4STJ.Test/Issues/Issue100.cs
> +                Converters = { new GeoJsonConverterFactory(fac, true) }
bbox is empty for Point geometries, that do not have a proper "bbox". maybe can be written "null" if the null values are allowed? 
BTW, very tricky to be consistent

2022-03-10 16:01 UTC, DGuidi commented
> Also, how soon usually does it take for a fix like this get into a released package?

**if** the PR is accepted by the maintainers, probably the package shoud be built manually (I suppose), so it depends ¯\_(ツ)_/¯

2022-03-10 16:30 UTC, airbreather requested changes

2022-03-10 16:30 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs
> +        public GeoJsonConverterFactory(GeometryFactory factory, bool writeBBox)
renaming a public parameter is a [breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/#modifications-to-the-public-contract)

2022-03-10 16:30 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.Envelope.cs
> +                value = env ?? new Envelope();
`env` cannot be `null` at this point, otherwise the `env.Area` check above would have thrown a `NullReferenceException`.

2022-03-10 16:30 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.Envelope.cs
> +        internal static void WriteBBox(Utf8JsonWriter writer, Envelope value, JsonSerializerOptions options, Envelope env)
it's very confusing to accept two separate `Envelope` parameters that we do two completely different things with, especially if their names are so similar

I don't have a specific suggestion what to do about this at this point

2022-03-10 16:45 UTC, DGuidi commented on test/NetTopologySuite.IO.GeoJSON4STJ.Test/Issues/Issue100.cs
> +                IgnoreNullValues = false,
it depends of the version of the system.text.json library referenced by the project

2022-03-10 16:47 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs
> +        public GeoJsonConverterFactory(GeometryFactory factory, bool writeBBox)
yep, you totally right. my bad. in my defense, in the meaning of the pr the original name can be misinterpreted, but I will restore the original names asap

2022-03-11 07:52 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.Envelope.cs
> +                value = env ?? new Envelope();
I will try to manage this differently, see below. any suggestions are well accepted, of course

2022-03-14 09:05 UTC, airbreather requested changes
Sorry for the longer delay, I needed to find some time with the code in a proper (not-GitHub) environment in order to tackle `WriteBBox`

2022-03-14 09:10 UTC, DGuidi commented
@airbreather  thanks for the deep analysis, I must admit that I have some of the same doubts you detected, but you found a lot of other potential inconsistencies :)
give me some time to understand a bit better how to fix this, and thanks again for the deep review.

2022-03-21 13:17 UTC, DGuidi commented
> I don't have a strong opinion on which of the two we should go for, though I will point out that the current version of the code seems to consistently do the first thing.

Thinking about this a bit, my idea is that the best thing to do is to simply trust `feature.BoundingBox` value. The code I wrote to compute the bbox based on "inner" elements (feature.geometry, feature elements in a collection, and it's geometries) seems a bit too complex to me for a library. It takes too much responsibilities that probably the client of the library should handle.

The current develop `WriteBBOX` method simply takes a [geometry object](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.Envelope.cs#L52), and it's used meaningfully only in the `FeatureWriter` as a [backup strategy](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjFeatureConverter.cs#L50).; it's totally ignored for [features collections](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjFeatureCollectionConverter.cs#L74) and it passes the same value twice [for geometries](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.cs#L233)

2022-03-22 11:10 UTC, airbreather approved these changes

2022-03-22 11:12 UTC, merged