Fix Issue #89
NetTopologySuite/NetTopologySuite.IO.GeoJSON pull request #90
Opened 2021-09-15 17:20 UTC by mymatthew

https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/issues/89

2021-09-15 17:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetTopologySuite/NetTopologySuite.IO.GeoJSON?pullRequest=90) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetTopologySuite/NetTopologySuite.IO.GeoJSON?pullRequest=90) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetTopologySuite/NetTopologySuite.IO.GeoJSON?pullRequest=90) it.</sub>

2022-01-17 13:35 UTC, DGuidi commented
can you please add a unit test that reproduces the error? at least to understand what do you mean for "Enumerable of Polygons" as input

2022-01-17 15:25 UTC, mymatthew commented
Yeah, It'll be a couple weeks before I get time, but I can add one.

Basically the test would be deserializing something built like this:
`var gf = NetTopologySuite.NtsGeometryServices.Instance.CreateGeometryFactory();
var polygonOne = gf.CreatPolygon();
var polygonTwo = gf.CreatePolygon();
IEnumerable<Polygon> testEnumeration = new[] { polygonOne, polygonTwo}`

The success of the test would be verifying that the deserialization results in an enumeration of items with a type of Polygon.
A second possibly success criteria would be that it deserializes without an error

2022-01-18 10:35 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
I'm pretty impressed that removing this line doesn't break any unit test...

2022-01-18 10:50 UTC, DGuidi commented
This is the unit test I've built
```
using NetTopologySuite.Geometries;
using NetTopologySuite.IO.Converters;
using Newtonsoft.Json;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace NetTopologySuite.IO.GeoJSON.Test.Issues.NetTopologySuite.IO.GeoJSON
{
    [GeoJsonIssueNumber(89)]
    public sealed class GitHubIssue89
    {
        [Test]
        public void TestEnumerableDeserialization()
        {
            var fac = GeometryFactory.Default;
            var p1 = fac.CreatePolygon(
                new LinearRing(new[]
                {
                    new Coordinate(-100, 45),
                    new Coordinate(-98, 45),
                    new Coordinate(-99, 46),
                    new Coordinate(-100, 45),
                }));
            var p2 = fac.CreatePolygon(
                new LinearRing(new[]
                {
                    new Coordinate(-101, 46),
                    new Coordinate(-99, 46),
                    new Coordinate(-100, 47),
                    new Coordinate(-101, 46),
                }));
            IEnumerable<Polygon> input = new[] { p1, p2 };

            var serializer = GeoJsonSerializer.CreateDefault();
            var sb = new StringBuilder();
            using (var sw = new StringWriter(sb))
            using (var jtw = new JsonTextWriter(sw))
            {
                serializer.Serialize(jtw, input);
            }
            string data = sb.ToString();
            Console.WriteLine(data);

            using var sr = new StringReader(data);
            using var jtr = new JsonTextReader(sr);
            object obj = serializer.Deserialize<IEnumerable<Polygon>>(jtr);
            Assert.That(obj, Is.Not.Null);
            Assert.That(obj, Is.InstanceOf<IEnumerable<Polygon>>());
            var ret = (IEnumerable<Polygon>)obj;
            Assert.That(input.ElementAt(0).EqualsExact(ret.ElementAt(0)), Is.True);
            Assert.That(input.ElementAt(1).EqualsExact(ret.ElementAt(1)), Is.True);
        }
    }
}
```

To let the test pass I had to add a fix also to `GeometryArrayConverter.ToCoordinate` method
from:
```
c.X = _factory.PrecisionModel.MakePrecise(Convert.ToDouble(array[0], formatProvider));
c.Y = _factory.PrecisionModel.MakePrecise(Convert.ToDouble(array[1], formatProvider));
```
to:
```
c.X = _factory.PrecisionModel.MakePrecise(Convert.ToDouble(((JValue)array[0]).Value, formatProvider));
c.Y = _factory.PrecisionModel.MakePrecise(Convert.ToDouble(((JValue)array[1]).Value, formatProvider));
```

2022-01-18 11:24 UTC, DGuidi commented
Same test for **_NetTopologySuite.IO.GeoJSON4STJ_**
```
using NetTopologySuite.Geometries;
using NetTopologySuite.IO.GeoJSON4STJ.Test.Converters;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace NetTopologySuite.IO.GeoJSON4STJ.Test.Issues
{
    [GeoJsonIssueNumber(89)]
    public sealed class Issue89 : SandDTest<IEnumerable<Geometry>>
    {
        private static IEnumerable<Geometry> CreateTestData()
        {
            var fac = GeometryFactory.Default;
            var p1 = fac.CreatePolygon(
                new LinearRing(new[]
                {
                    new Coordinate(-100, 45),
                    new Coordinate(-98, 45),
                    new Coordinate(-99, 46),
                    new Coordinate(-100, 45),
                }));
            var p2 = fac.CreatePolygon(
                new LinearRing(new[]
                {
                    new Coordinate(-101, 46),
                    new Coordinate(-99, 46),
                    new Coordinate(-100, 47),
                    new Coordinate(-101, 46),
                }));
            return new[] { p1, p2 };
        }

        [Test]
        public void TestEnumerableDeserialization()
        {
            var geoms = CreateTestData();
            string json;
            using (var ms = new MemoryStream())
            {
                Serialize(ms, geoms, DefaultOptions);
                json = Encoding.UTF8.GetString(ms.ToArray());
                Assert.That(string.IsNullOrWhiteSpace(json), Is.False);
                Console.WriteLine(json);
            }

            object tempObj = Deserialize(json, DefaultOptions);
            Assert.That(tempObj, Is.Not.Null);
            Assert.That(tempObj, Is.InstanceOf<List<Geometry>>());
            var serializedData = (List<Geometry>)tempObj;
            Assert.That(geoms.ElementAt(0).EqualsExact(serializedData[0]), Is.True);
            Assert.That(geoms.ElementAt(1).EqualsExact(serializedData[1]), Is.True);
        }
    }
}
```

2022-01-18 13:28 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> +            object[] jarray = array.Cast<JValue>().Select(i => i.Value).ToArray();
I don't like this code, but I see that also other methods (like ToCoordinates) assume that we are dealing with `JObject` types...

2022-01-18 14:15 UTC, airbreather requested changes
The reflection-based part of this is dangerous and unnecessary at best, broken at worst.  I don't see a new unit test proving that this won't explode when trying to deserialize something to, e.g., a `List<Polygon>`.  I cannot approve this until I see **at least** a new unit test confirming that this actually resolves the issue identified in #89, which would happen when trying to deserialize an `IEnumerable<Polygon>` (**NOT** an `IEnumerable<Geometry>`).
- My intuition is that this change *will not* actually fix the issue, and a unit test would prove it.  This is because the reflection-based test will try to cast an object of type `List<Polygon>` to `List<Geometry>`, which should not work (and if it does, then I would expect it to stop working at some point in the future).

In fact, if I'm looking at this correctly, this converter has always been more "broken" than it appears: it claims to be able to deserialize to any type that implements the `IEnumerable<Geometry>` interface (which, because `IEnumerable<out T>` is covariant, would include things like `IEnumerable<Polygon>`, but that's not an important part of this), but I believe that it would in fact fail if we tried to use it to deserialize even a `S.C.OM.Collection<Geometry>`, which has nothing to do with the issue of subtypes.

The root cause of #89 is that this type should never have been exposed publicly: it's not even used when deserializing `GeometryCollection` (maybe it used to be?), and it severely violates the contract of `JsonConverter`: there is no possible way for `ReadJson` to satisfy all the situations that `CanConvert` signs it up for, because it would require that we be able to fully support any arbitrary user-defined type that happens to implement that interface.

I believe that the fix should actually be something like how we fixed #31: deprecate this superfluous converter, and change `GeoJsonSerializer.AddGeoJsonConverters` to stop exposing it.  This will be a breaking change, but I believe that it is for the best.

*Disclaimer: I have not tried out any of this code, so if I'm severely off-course with my analysis, then perhaps it's OK to let this stand.  Note that I opened by mainly asking for a unit test that proves that it resolves the issue identified in #89, which should be as simple as changing the new test in `GitHubIssue89` to deserialize to an `IEnumerable<Polygon>` and re-running the test.*

2022-01-18 14:15 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> +            if (innerType != null)
If absolutely nothing else comes from my review feedback, then **at least** this check needs to be made narrower.

Rather than checking for generic type arguments on the type itself, we should check the single generic type argument on one of its interfaces, which satisfies the check from `CanConvert` that brought us in here.

As I'm writing in my summary, however, I believe that this type is defective overall and needs to go away.

2022-01-18 14:42 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> +            if (innerType != null)
thanks for the detailed feedback, actually the `IEnumerable<Polygon>` was the first version of the unit test, I just changed to IEnumerable<Geometry> to be a bit more generic... anyway, let me/us check deeply to your suggestions. I totally agree that more unit tests are needed and moreover that 

>  this converter has always been more "broken" than it appears

2022-01-18 16:14 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
@airbreather actually the only thing that is needed to deserialize a list of geometries as `IEnumerable<Geometry>` is to delete this `reader.Read()`, that simply looks broken to me.

2022-01-18 16:18 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
I agree.  Are the reflection-based changes actually fixing anything, then?  When I saw it during my review, it seemed like the intent of all that was to make it possible to deserialize as `IEnumerable<Polygon>`...

2022-01-19 06:24 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> Are the reflection-based changes actually fixing anything, then? 
basically, the reflection-based code allow the deserialization of a `IEnumerable<Polygon>`, or other kind of geometries, I suppose (tests needed) where the actual code (with the removal of the `reader.Read()` method, returns always `IEnumerable<Geometry>`.
I agree with you that having a list of actual polygons is the original purpose of @mymatthew PR, but I must admit that deserializing the data as list of the geometry base class seems a valid achievement to me, and with the benefit to not add dirty code to the `GeometryArrayConverter`.

2022-01-19 07:49 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
The deserialization of a IEnumerable<Geometry> seems to be also the actual behavior of `GeoJSON4STJ`, so another +1 for this.

2022-01-19 08:23 UTC, DGuidi commented
I don't know actually how to handle the PR, my idea is to merge "as is" and let the code handle the list of geometries as `List<Geometry>`, that is not what the original purpose of the PR is.

2022-01-19 13:15 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> The deserialization of a IEnumerable seems to be also the actual behavior of `GeoJSON4STJ`, so another +1 for this.

Because `System.Text.Json` works that way without doing anything special.

In fact, so does `Newtonsoft.Json`: the new test passes just fine on my machine (even when I change the `IEnumerable<Geometry>` to `IEnumerable<T>` for other `Geometry` subclasses) when all I do from `develop` is remove this converter from `GeoJsonSerializer.AddGeoJsonConverters`.

2022-01-19 13:44 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> > The deserialization of a IEnumerable seems to be also the actual behavior of `GeoJSON4STJ`, so another +1 for this.
> 
> Because `System.Text.Json` works that way without doing anything special.
> 
> In fact, so does `Newtonsoft.Json`: the new test passes just fine on my machine (even when I change the `IEnumerable<Geometry>` to `IEnumerable<T>` for other `Geometry` subclasses) when all I do from `develop` is remove this converter from `GeoJsonSerializer.AddGeoJsonConverters`.

And now that I set up my machine to run this code, I'm able to confirm that this PR **does not** support things like `IEnumerable<Polygon>`.  Removing this converter from the list **does** allow us to support those things.

2022-01-19 14:18 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
so basically we can just get rid of the `GeometryArrayConverter` class? 
WTF, what a waste of time from my side :)

2022-01-19 14:23 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> so basically we can just get rid of the `GeometryArrayConverter` class?

Well, that is what I suggested in my review summary:

> I believe that the fix should actually be something like how we fixed #31: deprecate this superfluous converter, and change `GeoJsonSerializer.AddGeoJsonConverters` to stop exposing it.  This will be a breaking change, but I believe that it is for the best.

I think there's a **possibility** that a few edge cases would start behaving differently, which is why I said "breaking change", but it really does seem like the way to go...

2022-01-19 14:42 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> Well, that is what I suggested in my review summary

yep, totally missed this. my bad and anyway I was just discussing, no bad feelings.

> but it really does seem like the way to go...

+1

2022-01-19 14:45 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> In fact, so does Newtonsoft.Json: the new test passes just fine on my machine (even when I change the 
 Enumerable<Geometry> to IEnumerable<T> for other Geometry subclasses) 

but, and I may be wrong, this doesn't seems to be the behavior of the `GeoJSON4STJ` library

2022-01-19 15:23 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> > In fact, so does Newtonsoft.Json: the new test passes just fine on my machine (even when I change the
> > Enumerable to IEnumerable for other Geometry subclasses)
> 
> confirmed for `GeoJSON` lib, but - and I may be wrong - this doesn't seems to be the behavior of the `GeoJSON4STJ` library

Works for me, here's my `Issue89.cs`: https://gist.github.com/airbreather/99565035a331fc6a12924e1dda8efcf3

2022-01-19 15:29 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
ok I see, the result of the deserialization is casted to the actual geometry used in the DoTest method, but the result of the Deserialization itself is still a `IEnumerable<Geometry>`.
Not sure this is a problem.

2022-01-19 15:37 UTC, airbreather commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
> ok I see, the result of the deserialization is casted to the actual geometry used in the DoTest method, but the result of the Deserialization itself is still a `IEnumerable<Geometry>`. Not sure this is a problem.

Yep, it is a problem, and I think I see why: I think it's because we extend `JsonConverter<Geometry>`.

I'll try to remember to open a new bug for this on the STJ side later, when I can get back to it.  For now, I'm cool with what we have here right now.

2022-01-19 15:37 UTC, airbreather approved these changes

2022-01-19 15:43 UTC, DGuidi commented on src/NetTopologySuite.IO.GeoJSON/Converters/GeometryArrayConverter.cs
> -            reader.Read();
thanks a lot I will commit the latest unit test code ASAP

2022-01-19 15:47 UTC, merged